[theme]
base = "dark"
primaryColor = "#00FFD1"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1A1C23"
textColor = "#FFFFFF"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
